### PR TITLE
Add failing test nested object reference during instance save

### PR DESCRIPTION
**Pull request by rywhee**

### CODE REVIEW

**Comment by juristr** [comment]
This deals with issue #21

**Comment by juristr** [comment]
@rywhee I think your failing test would need to be adjusted a bit in that the `$httpBackend` that mocks the real server needs to return the `kids` property:

```javascript
...
$httpBackend.expectPOST('/api/people', JSON.stringify(newModel)).respond(200, JSON.stringify({
    id: 12,
    name: 'Juri Strumpflohner',
    kids: children
}));
...
```

That doesn't fix your issue though. Your assert ` expect(newModel.kids).toBe(children);` still fails as we don't get the same object reference back..

I don't have time to look into it in more details right now, maybe tomorrow. @amcdnl What do you think. To fix this, the `shallowClearAndCopy(...)` would have to check whether a given property is an object and in case recursively go into it. Isn't that however the same `extendDeep(..)` does already??

**Comment by rywhee** [comment]
@juristr Yeah I agree, your update to `$httpBackend` is correct if we are keeping the behavior the same, and removing properties not returned from the server. Either way, the object reference is lost in the existing implementation. I'll update the test... Thanks!

**Comment by rywhee** [comment]
Updated to explicitly route around arrays to avoid the recursion, and simply take the array from destination. This helps avoid issues with order differences, etc. between the two arrays; and ends up being the same approach as what we currently do.

**Comment by juristr** [comment]
@rywhee Awesome :+1:  . I'll take a look at it later and merge it in.

**Comment by amcdnl** [comment]
@juristr thoughts?

**Comment by juristr** [comment]
@amcdnl @rywhee Seems ok to me. I wouldn't know of any other solution right now.

**Pull request merged**
