### PR TITLE
BUG: request params are not overriding defaults

### PR DESCRIPTION
**Pull request by rhutchison**

### CODE REVIEW

**Comment by rhutchison** [comment]
Updated [plnkr](http://plnkr.co/edit/sdVG0ly6COuuZIwXALrw?p=preview)

**Comment by juristr** [comment]
Will look into this, this weekend, promised :wink:

**Comment by juristr** [comment]
Ok, fixed it. Here's the plunkr with the updated source code: http://plnkr.co/edit/3fzqxI7tmy7ZKgXfWWHq?p=preview

@rhutchison Had to do some slight adjustments: https://github.com/Swimlane/angular-model-factory/blob/fix-defaults-overwriting/src/modelFactory.js#L623
Not sure where your `angular.merge` came from :wink: . 

@mmccook could you test it and give me some feedback? Simply take the model-factory file in the plunkr I linked which is the compiled version from [my branch](https://github.com/Swimlane/angular-model-factory/tree/fix-defaults-overwriting). If this modification is fine for you, I'll create a new release and deploy it on bower.

**Comment by juristr** [comment]
@rhutchison Ok, merged the changes in. For now I used our build-in `extendDeep` while merging (https://github.com/Swimlane/angular-model-factory/blob/master/src/modelFactory.js#L615) rather than `angular.merge` which would require angular `v1.4.x`. Not that upgrading would be an issue, we'll do it anyway, but for now we can remain backwards compatible.

let me know if this works for u, thx.

**Pull request closed without merging**
