### PR TITLE
support api metadata structure and add testcase

### PR DESCRIPTION
**Pull request by Ye-Ting**
add usecase backend respond with metadata

### CODE REVIEW

**Comment by Ye-Ting** [comment]
how i can link this pull-requests to issuse #28

**Comment by juristr** [comment]
@Ye-Ting You already referenced it by putting the link :wink: 

Btw, I added some comments to your code.  If you adjust them, I'm happy to merge it in. What's your view on this @amcdnl ?

**Comment by Ye-Ting** [comment]
Are there other problem ?

**Comment by Ye-Ting** [comment]
I need this feature ... 
or have any solutions?

**Comment by juristr** [comment]
@Ye-Ting I'll create a release later today (currently I'm quite busy).

**Comment by juristr** [comment]
@Ye-Ting Hi, just released v0.4.0 with your changes that support server-side metadata such as pagination. Thx for your effort :+1: and let me know if anything is wrong. :smile:

**Pull request merged**
