### PR TITLE
fix map bug

### PR DESCRIPTION
**Pull request by Ye-Ting**
fix map bug

### CODE REVIEW

**Comment by juristr** [comment]
@Ye-Ting could you add a test case that verifies the presence of this issue?? It's good to have that for preventing any further regression issues.

And thx for contributing :smile: !

**Comment by Ye-Ting** [comment]
I add a test case .
Is the usage your first thought ?
or have other problem ?

**Comment by juristr** [comment]
@Ye-Ting I'll merge it in later today. Thx for your effort!

**Comment by juristr** [comment]
@Ye-Ting I'm going to fix another thing I'm about to resolve in another branch and then I'll release a new version with your fix. Thx again!

**Pull request merged**
