### PR TITLE
adds failing test demonstrating a bug with cloned models

### PR DESCRIPTION
**Pull request by juristr**
I added this test which is failing as of now.

``` javascript
it('on a copied model it should sent back the copied model data', function(){
    var newModel = new PersonModel({
        name: 'Juri'
    });

    var copied = angular.copy(newModel);
    copied.name = 'Austin'; //change something in the clone

    $httpBackend.expectPOST('/api/people', JSON.stringify(copied)).respond(200, '');


    copied.$save();
    $httpBackend.flush();
});
```

When executing this test I get

image

**The scenario** is the following. Take the this simple master-detail editing UI:

image

When clicking on an item to start editing I want to update the list entry **only after the user clicked the save button and everything has been stored successfully on the server**, rather than the auto-updating scenario due to the live binding.

As such, I create a copy of the model using `angular.copy(...)` which I'm currently editing, for then merging it back into the original one once `$save()` succeeded. When doing so, I notice that `.copy(...)` does not work properly, at least not when then invoking `$save()` on the copied model as it will always take the data from original one rather than the newly copied.

I suspect it has something to do with [this line](https://github.com/phxdatasec/model-factory/blob/master/src/modelFactory.js#L335) as the data is somehow gathered from some internal variable.

@amcdnl Any idea on this? Or how we could fix it?

### CODE REVIEW

**Comment by juristr** [comment]
@amcdnl I'm still at home (sick) but on my way to get back up :) Had a bit of time to finish the PR solving the copy issue of a model.

I tried with `angular.copy` for a while, but that's not enough as I found. The problem is with lists (as we discussed in #19 ). When I take a model out of a list and I copy it, it still keeps the reference to the list internally. This might lead strange side-effects.

So in the end, I created a `$copy` instance function on the model which copies the raw values of the model into a new instance of it.

```javascript
instance.$copy = function(){
  // get the raw data of the model
  var rawData = Model.$strip(this);

  // ..then wrap it into a new instance
  return new Model(rawData);
};
```

In this way, invoking `someModelInstance.$copy()` on an existing model instance, creates a new instance with the old model's data.

What's your thought on this??

**Comment by amcdnl** [comment]
Few things:

- I had a $copy in there once upon a time and took it out for some reason that I can't remember.
- You might want to JSON the model vs stripping for object pointers internally ... probably slower but safer

**Comment by juristr** [comment]
So you mean to implement `$copy` differently in that I use `JSON.stringify(model)` or similar instead of `Model.$strip(...)`??

**Comment by amcdnl** [comment]
Ya, i think so

**Comment by juristr** [comment]
@amcdnl Like this?

```javascript
instance.$copy = function(){
  // get the raw data of the model
  var rawData = angular.toJson(this);

  // ..then wrap it into a new instance
  return new Model(angular.fromJson(rawData));
};
```

**Comment by amcdnl** [comment]
Ya I think so ...

**Comment by juristr** [comment]
@amcdnl Ok, changed the implementation with my last commit.

**Comment by amcdnl** [comment]
Merged.

**Pull request merged**
