### PR TITLE
Bug in $update()

### PR DESCRIPTION
**Pull request by elec29a**
Hi,

it seems like there is a bug in $update function

Best regards Hjh elec29a :)

### CODE REVIEW

**Comment by juristr** [comment]
@amcdnl :smile: Wanted to fix that anyway. It's a work mate of mine who I told to report the bug with a failing test.

Have to debug it on why it doesn't work..

**Comment by juristr** [comment]
@elec29a Will be fixed with the next release

**Comment by elec29a** [comment]
that's really good news :)
+1:  thumbs up great job

**Comment by juristr** [comment]
@elec29a Released v0.3.0 containing the fix for this bug. Should be out on bower soon

**Pull request closed without merging**
